global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: pushgateway
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true